spring.application.name=file_manager_cloudflare

spring.datasource.url=jdbc:postgresql://ep-silent-term-asfrhgmm.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true